# Generated by Django 6.0 on 2026-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day_type',
            field=models.CharField(choices=[('toq', 'Toq'), ('juft', 'Juft'), ('boshqa', 'Boshqa')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
